# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Waifu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('series', models.CharField(max_length=120)),
                ('rating', models.CharField(max_length=25)),
                ('height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('waifu_of_the_month', models.BooleanField()),
                ('img_url', models.CharField(max_length=200)),
            ],
        ),
    ]
